

INSERT INTO imp_causes_mt ( causes_item, is_active, created_by, created_on) VALUES 
('POVERTY', '1', 'SYSTEM', NOW()),
('HUNGER', '1', 'SYSTEM', NOW()),
('GOOD HEALTH AND WELL-BEING', '1', 'SYSTEM', NOW()),
('EDUCATION', '1', 'SYSTEM', NOW()),
('GENDER EQUALITY', '1', 'SYSTEM', NOW()),
('CLEAN WATER AND SANITATION', '1', 'SYSTEM', NOW()),
('AFFORDABLE AND CLEAN ENERGY', '1', 'SYSTEM', NOW()),
('DECENT WORK AND ECONOMIC GROWTH', '1', 'SYSTEM', NOW()),
('INDUSTRY, INNOVATION, AND INFRASTRUCTURE', '1', 'SYSTEM', NOW()),
('RACIAL AND ECONOMIC INEQUALITIES', '1', 'SYSTEM', NOW()),
('SUSTAINABLE CITIES AND COMMUNITIES', '1', 'SYSTEM', NOW()),
('RESPONSIBLE CONSUMPTION AND PRODUCTION', '1', 'SYSTEM', NOW()),
('CLIMATE ACTION', '1', 'SYSTEM', NOW()),
('LIFE BELOW WATER', '1', 'SYSTEM', NOW()),
('LIFE ON LAND', '1', 'SYSTEM', NOW()),
('PEACE, JUSTICE AND STRONG INSTITUTIONS', '1', 'SYSTEM', NOW());


INSERT INTO imp_interests_mt ( interest_item, is_active, created_by, created_on) VALUES 
('AInterest', '1', 'SYSTEM', NOW()),
('BInterest', '1', 'SYSTEM', NOW()),
('CInterest', '1', 'SYSTEM', NOW()),
('DInterest', '1', 'SYSTEM', NOW()),
('EInterest', '1', 'SYSTEM', NOW()),
('FInterest', '1', 'SYSTEM', NOW()),
('GInterest', '1', 'SYSTEM', NOW()),
('HInterest', '1', 'SYSTEM', NOW()),
('IInterest', '1', 'SYSTEM', NOW()),
('JInterest', '1', 'SYSTEM', NOW()),
('KInterest', '1', 'SYSTEM', NOW()),
('LInterest', '1', 'SYSTEM', NOW()),
('MInterest', '1', 'SYSTEM', NOW()),
('NInterest', '1', 'SYSTEM', NOW());


INSERT INTO imp_skills_mt ( skill_item, is_active, created_by, created_on) VALUES 
('Body Language', '1', 'SYSTEM', NOW()),
('Physical Communication', '1', 'SYSTEM', NOW()),
('Writing', '1', 'SYSTEM', NOW()),
('Storytelling', '1', 'SYSTEM', NOW()),
('Visual Communication', '1', 'SYSTEM', NOW()),
('Humor', '1', 'SYSTEM', NOW()),
('Quick-wittedness', '1', 'SYSTEM', NOW()),
('Listening', '1', 'SYSTEM', NOW()),
('Presentation Skills', '1', 'SYSTEM', NOW()),
('Public Speaking', '1', 'SYSTEM', NOW()),
('Interviewing', '1', 'SYSTEM', NOW()),

('Team Building', '1', 'SYSTEM', NOW()),
('Strategic Planning', '1', 'SYSTEM', NOW()),
('Coaching', '1', 'SYSTEM', NOW()),
('Mentoring', '1', 'SYSTEM', NOW()),
('Delegation', '1', 'SYSTEM', NOW()),
('Dispute Resolution', '1', 'SYSTEM', NOW()),
('Diplomacy', '1', 'SYSTEM', NOW()),
('Giving Feedback', '1', 'SYSTEM', NOW()),
('Managing Difficult Conversations', '1', 'SYSTEM', NOW()),
('Decision Making', '1', 'SYSTEM', NOW()),
('Performance Management', '1', 'SYSTEM', NOW()),
('Supervising', '1', 'SYSTEM', NOW()),
('Managing', '1', 'SYSTEM', NOW()),
('Manager Management', '1', 'SYSTEM', NOW()),
('Talent Management', '1', 'SYSTEM', NOW()),
('Managing Remote Teams', '1', 'SYSTEM', NOW()),
('Managing Virtual Teams', '1', 'SYSTEM', NOW()),
('Crisis Management', '1', 'SYSTEM', NOW()),

('Facilitation', '1', 'SYSTEM', NOW()),
('Selling', '1', 'SYSTEM', NOW()),
('Inspiring', '1', 'SYSTEM', NOW()),
('Persuasion', '1', 'SYSTEM', NOW()),
('Negotiation', '1', 'SYSTEM', NOW()),
('Motivating', '1', 'SYSTEM', NOW()),
('Collaborating', '1', 'SYSTEM', NOW()),

('Networking', '1', 'SYSTEM', NOW()),
('Interpersonal Relationships', '1', 'SYSTEM', NOW()),
('Dealing with Difficult People', '1', 'SYSTEM', NOW()),
('Conflict Resolution', '1', 'SYSTEM', NOW()),
('Personal Branding', '1', 'SYSTEM', NOW()),
('Office Politics', '1', 'SYSTEM', NOW()),

('Emotional Intelligence', '1', 'SYSTEM', NOW()),
('Self Awareness', '1', 'SYSTEM', NOW()),
('Emotion Management', '1', 'SYSTEM', NOW()),
('Stress Management', '1', 'SYSTEM', NOW()),
('Tolerance of Change and Uncertainty', '1', 'SYSTEM', NOW()),
('Taking Criticism', '1', 'SYSTEM', NOW()),
('Self Confidence', '1', 'SYSTEM', NOW()),
('Adaptability', '1', 'SYSTEM', NOW()),
('Resilience', '1', 'SYSTEM', NOW()),
('Assertiveness', '1', 'SYSTEM', NOW()),
('Competitiveness', '1', 'SYSTEM', NOW()),
('Self Leadership', '1', 'SYSTEM', NOW()),
('Self Assessment', '1', 'SYSTEM', NOW()),
('Work-Life Balance', '1', 'SYSTEM', NOW()),
('Friendliness', '1', 'SYSTEM', NOW()),
('Enthusiasm', '1', 'SYSTEM', NOW()),
('Empathy', '1', 'SYSTEM', NOW()),

('Problem Solving', '1', 'SYSTEM', NOW()),
('Critical Thinking', '1', 'SYSTEM', NOW()),
('Innovation', '1', 'SYSTEM', NOW()),
('Troubleshooting', '1', 'SYSTEM', NOW()),
('Design Sense', '1', 'SYSTEM', NOW()),
('Artistic Sense', '1', 'SYSTEM', NOW()),

('Organization', '1', 'SYSTEM', NOW()),
('Planning', '1', 'SYSTEM', NOW()),
('Scheduling', '1', 'SYSTEM', NOW()),
('Time Management', '1', 'SYSTEM', NOW()),
('Meeting Management', '1', 'SYSTEM', NOW()),
('Technology Savvy', '1', 'SYSTEM', NOW()),
('Technology Trend Awareness', '1', 'SYSTEM', NOW()),
('Business Trend Awareness', '1', 'SYSTEM', NOW()),
('Research', '1', 'SYSTEM', NOW()),
('Business Etiquette', '1', 'SYSTEM', NOW()),
('Business Ethics', '1', 'SYSTEM', NOW()),
('Diversity Awareness', '1', 'SYSTEM', NOW()),
('Disability Awareness', '1', 'SYSTEM', NOW()),
('Intercultural Competence', '1', 'SYSTEM', NOW()),
('Training', '1', 'SYSTEM', NOW()),
('Train the Trainer', '1', 'SYSTEM', NOW()),
('Process Improvement', '1', 'SYSTEM', NOW()),
('Knowledge Management', '1', 'SYSTEM', NOW()),
('Writing Reports and Proposals', '1', 'SYSTEM', NOW()),
('Customer Service', '1', 'SYSTEM', NOW()),
('Entrepreneurial Thinking', '1', 'SYSTEM', NOW()),

('Budgeting', '1', 'SYSTEM', NOW()),
('Business Planning', '1', 'SYSTEM', NOW()),
('Business Re-engineering', '1', 'SYSTEM', NOW()),
('Change Management', '1', 'SYSTEM', NOW()),
('Consolidation', '1', 'SYSTEM', NOW()),
('Cost Control', '1', 'SYSTEM', NOW()),
('Developing Policies', '1', 'SYSTEM', NOW()),
('Diversification', '1', 'SYSTEM', NOW()),
('Employee Evaluation', '1', 'SYSTEM', NOW()),
('Financing', '1', 'SYSTEM', NOW()),
('Government Relations', '1', 'SYSTEM', NOW()),
('Hiring', '1', 'SYSTEM', NOW()),
('International Management', '1', 'SYSTEM', NOW()),
('Investor Relations', '1', 'SYSTEM', NOW()),
('IPO Joint Ventures', '1', 'SYSTEM', NOW()),
('Labour Relations', '1', 'SYSTEM', NOW()),
('Merger & Acquisitions', '1', 'SYSTEM', NOW()),
('Multi-sites Management', '1', 'SYSTEM', NOW()),
('Profit & Loss', '1', 'SYSTEM', NOW()),
('Organizational Development', '1', 'SYSTEM', NOW()),

('Staff Development', '1', 'SYSTEM', NOW()),
('Strategic Partnership', '1', 'SYSTEM', NOW()),

('Supervision', '1', 'SYSTEM', NOW()),

('Bidding', '1', 'SYSTEM', NOW()),
('Call Centre Operations', '1', 'SYSTEM', NOW()),
('Continuous Improvement', '1', 'SYSTEM', NOW()),
('Contract Management', '1', 'SYSTEM', NOW()),
('Environmental Protection', '1', 'SYSTEM', NOW()),
('Facility Management', '1', 'SYSTEM', NOW()),
('Inventory Control', '1', 'SYSTEM', NOW()),
('Manpower Planning', '1', 'SYSTEM', NOW()),
('Operations Research', '1', 'SYSTEM', NOW()),
('Outsourcing', '1', 'SYSTEM', NOW()),
('Policies & Procedures', '1', 'SYSTEM', NOW()),
('Project Co-ordination', '1', 'SYSTEM', NOW()),
('Project Management', '1', 'SYSTEM', NOW()),

('Equipment Design', '1', 'SYSTEM', NOW()),
('Equipment Maintenance & Repair', '1', 'SYSTEM', NOW()),
('Equipment Management', '1', 'SYSTEM', NOW()),
('Order Processing', '1', 'SYSTEM', NOW()),
('Plant Design & Layout', '1', 'SYSTEM', NOW()),
('Process Engineering', '1', 'SYSTEM', NOW()),
('Production Planning', '1', 'SYSTEM', NOW()),
('Quality Assurance', '1', 'SYSTEM', NOW()),
('Safety Engineering', '1', 'SYSTEM', NOW());

